version: '2'
services:
  mysql:
    image: mysql:8.0.43
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
  php:
    image: yiisoftware/yii2-php:8.4-fpm-latest-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    depends_on:
      - mysql
    ports:
      - '8000:80'
  migrate:
    image: yiisoftware/yii2-php:8.4-fpm-latest-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    depends_on:
      - mysql
    command: php yii migrate --interactive=0